export const playerImages = [
  {
    name: "James Trafford",
    prefferedName: "Trafford",
    verticalImage: "/players-image/james-trafford-vertical.webp",
    roundImage: "/players-image/james-trafford-round.png",
    alt: "James Trafford",
    value: "james-trafford",
  },
  {
    name: "Marcus Bettinelli",
    prefferedName: "Bettinelli",
    verticalImage: "/players-image/marcus-bettinelli-vertical.webp",
    roundImage: "/players-image/marcus-bettinelli-round.png",
    alt: "Marcus Bettinelli",
    value: "marcus-bettinelli",
  },
  {
    name: "Gianluigi Donnarumma",
    prefferedName: "Donnarumma",
    verticalImage: "/players-image/donnaruma-vertical.webp",
    roundImage: "/players-image/donnaruma-round.png",
    alt: "Gianluigi Donnarumma",
    value: "gianluigi-donnarumma",
  },
  {
    name: "Matheus Nunes",
    prefferedName: "Nunes",
    verticalImage: "/players-image/matheus-nunes-vertical.webp",
    roundImage: "/players-image/matheus-nunes-round.png",
    alt: "Matheus Nunes",
    value: "matheus-nunes",
  },
  {
    name: "Rico Lewis",
    prefferedName: "Lewis",
    verticalImage: "/players-image/rico-lewis-vertical.webp",
    roundImage: "/players-image/rico-lewis-round.png",
    alt: "Rico Lewis",
    value: "rico-lewis",
  },
  {
    name: "Vitor Reis",
    prefferedName: "Reis",
    verticalImage: "/players-image/vitor-reis-vertical.webp",
    roundImage: "/players-image/vitor-reis-round.png",
    alt: "Vitor Reis",
    value: "vitor-reis",
  },
  {
    name: "Ruben Dias",
    prefferedName: "Dias",
    verticalImage: "/players-image/ruben-dias-vertical.webp",
    roundImage: "/players-image/ruben-dias-round.png",
    alt: "Rúben Dias",
    value: "ruben-dias",
  },
  {
    name: "Marc Guehi",
    prefferedName: "Guehi",
    verticalImage: "/players-image/marc-gue-vertical.webp",
    roundImage: "/players-image/marc-gue-round.png",
    alt: "Marc Guéhi",
    value: "marc-guehi",
  },
  {
    name: "Josko Gvardiol",
    prefferedName: "Gvardiol",
    verticalImage: "/players-image/josko-gvardiol-vertical.webp",
    roundImage: "/players-image/josko-gvardiol-round.png",
    alt: "Josko Gvardiol",
    value: "josko-gvardiol",
  },
  {
    name: "Abdukodir Khusanov",
    prefferedName: "Khusanov",
    verticalImage: "/players-image/abdukodir-khusanov-vertical.webp",
    roundImage: "/players-image/abdukodir-khusanov-round.png",
    alt: "Abdukodir Khusanov",
    value: "abdukodir-khusanov",
  },
  {
    name: "Max Alleyne",
    prefferedName: "Alleyne",
    verticalImage: "/players-image/max-alleyne-vertical.webp",
    roundImage: "/players-image/max-alleyne-round.png",
    alt: "Max Alleyne",
    value: "max-alleyne",
  },
  {
    name: "Rayan Ait-Nouri",
    prefferedName: "RAN",
    verticalImage: "/players-image/rayan-ait-nouri-vertical.webp",
    roundImage: "/players-image/rayan-ait-nouri-round.png",
    alt: "Rayan Aït-Nouri",
    value: "rayan-ait-nouri",
  },
  {
    name: "Nico O'Reilly",
    prefferedName: "NOR",
    verticalImage: "/players-image/nico-oreilly-vertical.webp",
    roundImage: "/players-image/nico-oreilly-round.png",
    alt: "Nico O'Reilly",
    value: "nico-oreilly",
  },
  {
    name: "Elliot Anderson",
    prefferedName: "Anderson",
    verticalImage: "/players-image/elliot-vertical.webp",
    roundImage: "/players-image/elliot-round.png",
    alt: "Elliot Anderson",
    value: "elliot",
  },
  {
    name: "Mateo Kovacic",
    prefferedName: "Kovacic",
    verticalImage: "/players-image/mateo-kovacic-vertical.webp",
    roundImage: "/players-image/mateo-kovacic-round.png",
    alt: "Mateo Kovacic",
    value: "mateo-kovacic",
  },
  {
    name: "Nico González",
    prefferedName: "Nico G",
    verticalImage: "/players-image/nico-gonzalez-vertical.webp",
    roundImage: "/players-image/nico-gonzalez-round.png",
    alt: "Nico González",
    value: "nico-gonzalez",
  },
  {
    name: "Rodri",
    prefferedName: "Rodri",
    verticalImage: "/players-image/rodri-vertical.webp",
    roundImage: "/players-image/rodri-round.png",
    alt: "Rodri",
    value: "rodri",
  },
  {
    name: "Kalvin Phillips",
    prefferedName: "Phillips",
    verticalImage: "/players-image/kalvin-phillips-vertical.webp",
    roundImage: "/players-image/kalvin-phillips-round.png",
    alt: "Kalvin Phillips",
    value: "kalvin-phillips",
  },
  {
    name: "Tijjani Reijnders",
    prefferedName: "Reijnders",
    verticalImage: "/players-image/tijjani-reijnders-vertical.webp",
    roundImage: "/players-image/tijjani-reijnders-round.png",
    alt: "Tijjani Reijnders",
    value: "tijjani-reijnders",
  },
  {
    name: "Rayan Cherki",
    prefferedName: "Cherki",
    verticalImage: "/players-image/rayan-cherki-vertical.webp",
    roundImage: "/players-image/rayan-cherki-round.png",
    alt: "Rayan Cherki",
    value: "rayan-cherki",
  },
  {
    name: "Sverre Halseth Nypan",
    prefferedName: "Nypan",
    verticalImage: "/players-image/sverre-nypan-vertical.webp",
    roundImage: "/players-image/sverre-nypan-round.png",
    alt: "Sverre Halseth Nypan",
    value: "sverre-halseth-nypan",
  },
  {
    name: "Phil Foden",
    prefferedName: "Foden",
    verticalImage: "/players-image/phil-foden-vertical.webp",
    roundImage: "/players-image/phil-foden-round.png",
    alt: "Phil Foden",
    value: "phil-foden",
  },
  {
    name: "Antoine Semenyo",
    prefferedName: "Semenyo",
    verticalImage: "/players-image/semenyo-vertical.webp",
    roundImage: "/players-image/semenyo-round.png",
    alt: "Antoine Semenyo",
    value: "antoine-semenyo",
  },
  {
    name: "Jack Grealish",
    prefferedName: "Grealish",
    verticalImage: "/players-image/jack-grealish-vertical.webp",
    roundImage: "/players-image/jack-grealish-round.png",
    alt: "Jack Grealish",
    value: "jack-grealish",
  },
  {
    name: "Jeremy Doku",
    prefferedName: "Doku",
    verticalImage: "/players-image/jeremy-doku-vertical.webp",
    roundImage: "/players-image/jeremy-doku-round.png",
    alt: "Jérémy Doku",
    value: "jeremy-doku",
  },
  {
    name: "Savinho",
    prefferedName: "Savinho",
    verticalImage: "/players-image/savinho-vertical.webp",
    roundImage: "/players-image/savinho-round.png",
    alt: "Savinho",
    value: "savinho",
  },
  {
    name: "Claudio Echeverri",
    prefferedName: "Echeverri",
    verticalImage: "/players-image/claudio-echeverri-vertical.webp",
    roundImage: "/players-image/claudio-echeverri-round.png",
    alt: "Claudio Echeverri",
    value: "claudio-echeverri",
  },
  {
    name: "Omar Marmoush",
    prefferedName: "Marmoush",
    verticalImage: "/players-image/omar-marmoush-vertical.webp",
    roundImage: "/players-image/omar-marmoush-round.png",
    alt: "Omar Marmoush",
    value: "omar-marmoush",
  },
  {
    name: "Erling Haaland",
    prefferedName: "Haaland",
    verticalImage: "/players-image/erling-haaland-vertical.webp",
    roundImage: "/players-image/erling-haaland-round.png",
    alt: "Erling Haaland",
    value: "erling-haaland",
  },
  {
    name: "Vinicius Junior",
    prefferedName: "Vini",
    verticalImage: "/players-image/vini-vertical.webp",
    roundImage: "/players-image/vini-round.png",
    alt: "Vinicius Junior",
    value: "vinicius-junior",
  },
  {
    name: "Yan Diomande",
    prefferedName: "Diomande",
    verticalImage: "/players-image/diomande-vertical.webp",
    roundImage: "/players-image/diomande-round.png",
    alt: "Yan Diomande",
    value: "yan-diomande",
  },
  {
    name: "Ayyoub Bouaddi",
    prefferedName: "Bouaddi",
    verticalImage: "/players-image/bouaddi-vertical.webp",
    roundImage: "/players-image/bouaddi-round.png",
    alt: "Ayyoub Bouaddi",
    value: "ayyoub-bouaddi",
  },
  {
    name: "Divin Mubama",
    prefferedName: "Mubama",
    verticalImage: "/players-image/mubama-vertical.webp",
    roundImage: "/players-image/mubama-round.png",
    alt: "Divin Mubama",
    value: "divin-mubama",
  },
  {
    name: "Stephen Mfuni",
    prefferedName: "Mfuni",
    verticalImage: "/players-image/mfuni-vertical.webp",
    roundImage: "/players-image/mfuni-round.png",
    alt: "Stephen Mfuni",
    value: "stephen-mfuni",
  },
  {
    name: "Ryan McAidoo",
    prefferedName: "McAidoo",
    verticalImage: "/players-image/mcaidoo-vertical.webp",
    roundImage: "/players-image/mcaidoo-round.png",
    alt: "Ryan McAidoo",
    value: "ryan-mcaidoo",
  },
  {
    name: "Mahamadou Sangare",
    prefferedName: "Sangare",
    verticalImage: "/players-image/sangare-vertical.webp",
    roundImage: "/players-image/sangare-round.png",
    alt: "Mahamadou Sangare",
    value: "mahamadou-sangare",
  },
  {
    name: "Kaden Braithwaite",
    prefferedName: "Braithwaite",
    verticalImage: "/players-image/braithwaite-vertical.webp",
    roundImage: "/players-image/braithwaite-round.png",
    alt: "Kaden Braithwaite",
    value: "kaden-braithwaite",
  },
];
