export const playerImages = [
  {
    name: "James Trafford",
    verticalImage: "/players-image/james-trafford-vertical.webp",
    roundImage: "/players-image/james-trafford-round.png",
    alt: "James Trafford",
    value: "james-trafford",
  },
  {
    name: "Marcus Bettinelli",
    verticalImage: "/players-image/marcus-bettinelli-vertical.webp",
    roundImage: "/players-image/marcus-bettinelli-round.png",
    alt: "Marcus Bettinelli",
    value: "marcus-bettinelli",
  },
  {
    name: "Gianluigi Donnarumma",
    verticalImage: "/players-image/gianluigi-donnarumma-vertical.webp",
    roundImage: "/players-image/gianluigi-donnarumma-round.png",
    alt: "Gianluigi Donnarumma",
    value: "gianluigi-donnarumma",
  },
  {
    name: "Matheus Nunes",
    verticalImage: "/players-image/matheus-nunes-vertical.webp",
    roundImage: "/players-image/matheus-nunes-round.png",
    alt: "Matheus Nunes",
    value: "matheus-nunes",
  },
  {
    name: "Rico Lewis",
    verticalImage: "/players-image/rico-lewis-vertical.webp",
    roundImage: "/players-image/rico-lewis-round.png",
    alt: "Rico Lewis",
    value: "rico-lewis",
  },
  {
    name: "Vitor Reis",
    verticalImage: "/players-image/vitor-reis-vertical.webp",
    roundImage: "/players-image/vitor-reis-round.png",
    alt: "Vitor Reis",
    value: "vitor-reis",
  },
  {
    name: "Rúben Dias",
    verticalImage: "/players-image/ruben-dias-vertical.webp",
    roundImage: "/players-image/ruben-dias-round.png",
    alt: "Rúben Dias",
    value: "ruben-dias",
  },
  {
    name: "Marc Guéhi",
    verticalImage: "/players-image/marc-guehi-vertical.webp",
    roundImage: "/players-image/marc-guehi-round.png",
    alt: "Marc Guéhi",
    value: "marc-guehi",
  },
  {
    name: "Josko Gvardiol",
    verticalImage: "/players-image/josko-gvardiol-vertical.webp",
    roundImage: "/players-image/josko-gvardiol-round.png",
    alt: "Josko Gvardiol",
    value: "josko-gvardiol",
  },
  {
    name: "Abdukodir Khusanov",
    verticalImage: "/players-image/abdukodir-khusanov-vertical.webp",
    roundImage: "/players-image/abdukodir-khusanov-round.png",
    alt: "Abdukodir Khusanov",
    value: "abdukodir-khusanov",
  },
  {
    name: "Max Alleyne",
    verticalImage: "/players-image/max-alleyne-vertical.webp",
    roundImage: "/players-image/max-alleyne-round.png",
    alt: "Max Alleyne",
    value: "max-alleyne",
  },
  {
    name: "Josh Wilson-Esbrand",
    verticalImage: "/players-image/josh-wilson-esbrand-vertical.webp",
    roundImage: "/players-image/josh-wilson-esbrand-round.png",
    alt: "Josh Wilson-Esbrand",
    value: "josh-wilson-esbrand",
  },
  {
    name: "Rayan Aït-Nouri",
    verticalImage: "/players-image/rayan-ait-nouri-vertical.webp",
    roundImage: "/players-image/rayan-ait-nouri-round.png",
    alt: "Rayan Aït-Nouri",
    value: "rayan-ait-nouri",
  },
  {
    name: "Nico O'Reilly",
    verticalImage: "/players-image/nico-oreilly-vertical.webp",
    roundImage: "/players-image/nico-oreilly-round.png",
    alt: "Nico O'Reilly",
    value: "nico-oreilly",
  },
  {
    name: "Issa Kaboré",
    verticalImage: "/players-image/issa-kabore-vertical.webp",
    roundImage: "/players-image/issa-kabore-round.png",
    alt: "Issa Kaboré",
    value: "issa-kabore",
  },
  {
    name: "Elliot Anderson",
    verticalImage: "/players-image/elliot-anderson-vertical.webp",
    roundImage: "/players-image/elliot-anderson-round.png",
    alt: "Elliot Anderson",
    value: "elliot-anderson",
  },
  {
    name: "Mateo Kovacic",
    verticalImage: "/players-image/mateo-kovacic-vertical.webp",
    roundImage: "/players-image/mateo-kovacic-round.png",
    alt: "Mateo Kovacic",
    value: "mateo-kovacic",
  },
  {
    name: "Nico González",
    verticalImage: "/players-image/nico-gonzalez-vertical.webp",
    roundImage: "/players-image/nico-gonzalez-round.png",
    alt: "Nico González",
    value: "nico-gonzalez",
  },
  {
    name: "Rodri",
    verticalImage: "/players-image/rodri-vertical.webp",
    roundImage: "/players-image/rodri-round.png",
    alt: "Rodri",
    value: "rodri",
  },
  {
    name: "Kalvin Phillips",
    verticalImage: "/players-image/kalvin-phillips-vertical.webp",
    roundImage: "/players-image/kalvin-phillips-round.png",
    alt: "Kalvin Phillips",
    value: "kalvin-phillips",
  },
  {
    name: "Tijjani Reijnders",
    verticalImage: "/players-image/tijjani-reijnders-vertical.webp",
    roundImage: "/players-image/tijjani-reijnders-round.png",
    alt: "Tijjani Reijnders",
    value: "tijjani-reijnders",
  },
  {
    name: "Rayan Cherki",
    verticalImage: "/players-image/rayan-cherki-vertical.webp",
    roundImage: "/players-image/rayan-cherki-round.png",
    alt: "Rayan Cherki",
    value: "rayan-cherki",
  },
  {
    name: "Sverre Halseth Nypan",
    verticalImage: "/players-image/sverre-halseth-nypan-vertical.webp",
    roundImage: "/players-image/sverre-halseth-nypan-round.png",
    alt: "Sverre Halseth Nypan",
    value: "sverre-halseth-nypan",
  },
  {
    name: "Phil Foden",
    verticalImage: "/players-image/phil-foden-vertical.webp",
    roundImage: "/players-image/phil-foden-round.png",
    alt: "Phil Foden",
    value: "phil-foden",
  },
  {
    name: "Ryan McAidoo",
    verticalImage: "/players-image/ryan-mcaidoo-vertical.webp",
    roundImage: "/players-image/ryan-mcaidoo-round.png",
    alt: "Ryan McAidoo",
    value: "ryan-mcaidoo",
  },
  {
    name: "Antoine Semenyo",
    verticalImage: "/players-image/antoine-semenyo-vertical.webp",
    roundImage: "/players-image/antoine-semenyo-round.png",
    alt: "Antoine Semenyo",
    value: "antoine-semenyo",
  },
  {
    name: "Jack Grealish",
    verticalImage: "/players-image/jack-grealish-vertical.webp",
    roundImage: "/players-image/jack-grealish-round.png",
    alt: "Jack Grealish",
    value: "jack-grealish",
  },
  {
    name: "Jérémy Doku",
    verticalImage: "/players-image/jeremy-doku-vertical.webp",
    roundImage: "/players-image/jeremy-doku-round.png",
    alt: "Jérémy Doku",
    value: "jeremy-doku",
  },
  {
    name: "Savinho",
    verticalImage: "/players-image/savinho-vertical.webp",
    roundImage: "/players-image/savinho-round.png",
    alt: "Savinho",
    value: "savinho",
  },
  {
    name: "Claudio Echeverri",
    verticalImage: "/players-image/claudio-echeverri-vertical.webp",
    roundImage: "/players-image/claudio-echeverri-round.png",
    alt: "Claudio Echeverri",
    value: "claudio-echeverri",
  },
  {
    name: "Omar Marmoush",
    verticalImage: "/players-image/omar-marmoush-vertical.webp",
    roundImage: "/players-image/omar-marmoush-round.png",
    alt: "Omar Marmoush",
    value: "omar-marmoush",
  },
  {
    name: "Erling Haaland",
    verticalImage: "/players-image/erling-haaland-vertical.webp",
    roundImage: "/players-image/erling-haaland-round.png",
    alt: "Erling Haaland",
    value: "erling-haaland",
  },
];
