export const clubLogos = [
  {
    title: "AFC Bournemouth",
    value: "afc-bournemouth",
    path: "/club-logos/Bournemouth.webp",
    alt: "AFC Bournemouth",
  },
  {
    title: "Arsenal",
    value: "arsenal",
    path: "/club-logos/Arsenal.webp",
    alt: "Arsenal",
  },
  {
    title: "Aston Villa",
    value: "aston-villa",
    path: "/club-logos/Aston_Villa.webp",
    alt: "Aston Villa",
  },
  {
    title: "Brentford",
    value: "brentford",
    path: "/club-logos/Brentford.webp",
    alt: "Brentford",
  },
  {
    title: "Brighton & Hove Albion",
    value: "brighton-hove-albion",
    path: "/club-logos/Brighton_and_Hove_Albion.webp",
    alt: "Brighton & Hove Albion",
  },
  {
    title: "Chelsea",
    value: "chelsea",
    path: "/club-logos/Chelsea.webp",
    alt: "Chelsea",
  },
  {
    title: "Coventry City",
    value: "coventry-city",
    path: "/club-logos/Coventry_City.webp",
    alt: "Coventry City",
  },
  {
    title: "Crystal Palace",
    value: "crystal-palace",
    path: "/club-logos/Crystal_Palace.webp",
    alt: "Crystal Palace",
  },
  {
    title: "Everton",
    value: "everton",
    path: "/club-logos/Everton.webp",
    alt: "Everton",
  },
  {
    title: "Fulham",
    value: "fulham",
    path: "/club-logos/Fulham.webp",
    alt: "Fulham",
  },
  {
    title: "Hull City",
    value: "hull-city",
    path: "/club-logos/Hull_City.webp",
    alt: "Hull City",
  },
  {
    title: "Ipswich Town",
    value: "ipswich-town",
    path: "/club-logos/Ipswich_Town.webp",
    alt: "Ipswich Town",
  },
  {
    title: "Leeds United",
    value: "leeds-united",
    path: "/club-logos/Leeds_United.webp",
    alt: "Leeds United",
  },
  {
    title: "Liverpool",
    value: "liverpool",
    path: "/club-logos/Liverpool.webp",
    alt: "Liverpool",
  },
  {
    title: "Manchester City",
    value: "manchester-city",
    path: "/club-logos/Manchester_City.webp",
    alt: "Manchester City",
  },
  {
    title: "Manchester United",
    value: "manchester-united",
    path: "/club-logos/Manchester_United.webp",
    alt: "Manchester United",
  },
  {
    title: "Newcastle United",
    value: "newcastle-united",
    path: "/club-logos/Newcastle_United.webp",
    alt: "Newcastle United",
  },
  {
    title: "Nottingham Forest",
    value: "nottingham-forest",
    path: "/club-logos/Nottingham_Forest.webp",
    alt: "Nottingham Forest",
  },
  {
    title: "Sunderland",
    value: "sunderland",
    path: "/club-logos/Sunderland.webp",
    alt: "Sunderland",
  },
  {
    title: "Tottenham Hotspur",
    value: "tottenham-hotspur",
    path: "/club-logos/Tottenham_Hotspur.webp",
    alt: "Tottenham Hotspur",
  },
  {
    title: "Athletico Madrid",
    value: "athletico-madrid",
    path: "/club-logos/Atletico_Madrid.webp",
    alt: "Athletico Madrid",
  },
  {
    title: "Inter Milan",
    value: "inter-milan",
    path: "/club-logos/inter-milan.webp",
    alt: "Inter Milan",
  },
  {
    title: "K League All Stars",
    value: "K_League_All_Stars",
    path: "/club-logos/K_League.webp",
    alt: "K_League_All_Stars",
  },
];
